version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: npm
    versions:
    - 6.14.10
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
  - dependency-name: typescript
    versions:
    - 3.9.7
